name = "SlimPlotting"
uuid = "f6d04670-764e-495b-a720-91c3c9a588ff"
authors = ["Mathias Louboutin <mathias.louboutin@gmail.com>"]
version = "0.1.3"

[deps]
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
ColorSchemes = "3"
PyPlot = "2"
julia = "1"
