name: Documentation

on:
  push:
    branches:
      - master
    tags: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JULIA_NUM_THREADS: 1

    steps:
      - uses: actions/checkout@v2
      
      - uses: julia-actions/setup-julia@latest
  
      - name: Build SlimPlotting
        uses: julia-actions/julia-buildpkg@latest

      - name: Install dependencies
        run: |
          julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
          julia -e 'using Pkg; Pkg.add("PythonPlot")'
  
      - name: Setup README
        run: cp README.md docs/src/README.md

      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For authentication with GitHub Actions token
        run: julia --project=docs/ docs/make.jl
