name: Documentation

on:
  push:
    branches:
      - master
    tags: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: julia-actions/setup-julia@latest
      
      - name: Install dependencies
        run: |
          /usr/bin/python3 -m pip install matplotlib colorcet
          julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
      
      - name: Setup README
        run: cp README.md docs/src/README.md

      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For authentication with GitHub Actions token
        run: julia --project=docs/ docs/make.jl
